# Learning R for Data Science

## R Programming
**Assigning data to a variable:**\
```x <- 5```\
**To display a variable:**\
Either: ```print(x)``` or ```x```\
**Create an integer vector**\
```x <- 1:20```\
**Explicit Coercion**\
```x <- 0:6```
Use the as function with methods: numeric, logical, complex or character:\
```as.character(x)```\
**Lists**\
```x <- list(1, "a", T)```\
**Matrices**\
```m <- matrix(1:6, nrow=2, ncol=3)```\
To return the number of rows, columns: ```dim(m)```\
Matrices are created column wise so the above matrix will look like this:\
     [,1] [,2] [,3]\
[1,]    1    3    5\
[2,]    2    4    6\
To bind two vectors use cbind and rbind (column and row bind)
*Convert a Vector to a Matrix*\
```m <- 1:10
dim(m) <- c(2,5)```\
**Factors**\
Factors are created using the factor function\
The input into the factor function is a character vector.\
```x <- factor(c("yes", "yes", "no", "yes", "no"))```\
The levels of this factor are yes and no.\
```table(x)``` gives you a frequency count of each level of how many their are.\
```unclass(x)``` will convert the factor to an integter factor, \
but the levels attributes are still yes and no.\

## R Functions
Save file as .R -> load file into console using source("myfile.R") ->\
check which functions are available using ls() -> call function: myfunction()

## R
R comes from S which was developed by John Chambers. \
R was created by Ross Ihaka and Robert Gentleman (From New Zealand).


## GitHub
1.) Commit changed files.\
2.) Push committed files.